version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      #MYSQL_USER: homestead
      #MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysqldb:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=rootsecret
    ports:
      - "8091:80"
    depends_on:
      - mysql
    networks:
      - laravel
      
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - php
    networks:
      - laravel

  npm:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: npm
    volumes: 
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - php
      - mysql
    entrypoint: ['npm']
    networks: 
      - laravel
